name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
    uses: "getpelican/pelican/.github/workflows/github_pages.yml@main"
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    with:
      settings: "publishconf.py"
      requirements: "pelican[markdown] pelican-seo pelican-sitemap pelican-injector minchin-pelican-plugins-nojekyll"
      theme: "https://github.com/max-pfeiffer/pelican-hyde"
